name: Deploymentaav

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - master

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - uses: actions/setup-node@master
        - run: npm install
        - run: npm run build





#   movefile:
#         uses: SamKirkland/FTP-Deploy-Action@4.3.0
#         with:
#             server: kaboompress.com
#             username: animationbrunch
#             password: Animation4brunch#01
#             protocol: ftp
#             port: 21 # todo replace with your web hosts ftps port
#             server-dir: ./deployed_sites/ghost.fahrenheit451house.com/
#             local-dir: ./
# #             dangerous-clean-slate: true
